package Form;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import Config.koneksi;
import java.sql.ResultSet;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.design.JRDesignQuery;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author windows7
 */
public class Laporan extends javax.swing.JFrame {
    koneksi con = new koneksi();
    ResultSet rs;
    JasperReport jasrep;
    JasperPrint jaspri;
    //HashMap map = new HashMap();
    JasperDesign design;
    DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
    Calendar cal = Calendar.getInstance();
    /**
     * Creates new form Statistics
     */
    public Laporan() {
        super("Laporan");
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tgl1 = new com.toedter.calendar.JDateChooser();
        tgl2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 143, 182));
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Laporan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(468, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-", "Laporan Peminjaman", "Laporan Pengembalian", "Laporan Databarang", "Laporan DetailPinjam" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Pilih Laporan");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/printer (1).png"))); // NOI18N
        jButton1.setText("  Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tgl1.setDateFormatString("dd-MM-yyyy");

        tgl2.setDateFormatString("dd-MM-yyyy");

        jLabel3.setText("Dari Tanggal");

        jLabel4.setText("Sampai Tanggal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tgl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tgl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, 198, Short.MAX_VALUE))))
                .addGap(84, 84, 84))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tgl1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tgl2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1AncestorMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String d_dari = dateFormat.format(tgl1.getDate());
        String d_sampai = dateFormat.format(tgl2.getDate());

        if(jComboBox1.getSelectedItem().equals("Laporan Peminjaman")) {
            try {
                //map.put("d_dari", d_dari);
                //map.put("d_sampai" , d_sampai);
                File report = new File("src/Laporan/peminjaman_dipinjam.jrxml");
                design = JRXmlLoader.load(report);
                String sql = "SELECT peminjaman.`id_peminjaman` AS peminjaman_id_peminjaman,"
                        + "peminjaman.`kode_inventaris` AS peminjaman_kode_inventaris,"
                        + "peminjaman.`tanggal_pinjam` AS peminjaman_tanggal_pinjam,"
                        + "peminjaman.`tanggal_kembali` AS peminjaman_tanggal_kembali,"
                        + "peminjaman.`status_peminjaman` AS peminjaman_status_peminjaman,"
                        + "peminjaman.`identitas_peminjam` AS peminjaman_identitas_peminjam,"
                        + "peminjaman.`jumlah_pinjam` AS peminjaman_jumlah_pinjam "
                        + "FROM `peminjaman` peminjaman where status_peminjaman='Dipinjam'"
                        + "AND tanggal_pinjam BETWEEN '"+ d_dari+"' and '"+d_sampai+"'";
                JRDesignQuery query=new JRDesignQuery();
                query.setText(sql);
                design.setQuery(query);
                jasrep = JasperCompileManager.compileReport(design);
                jaspri = JasperFillManager.fillReport(jasrep, null, con.getconnetion());
                JasperViewer.viewReport(jaspri,false);
            } catch (Exception e) {
                System.out.println(e);
            }

        } else if(jComboBox1.getSelectedItem().equals("Laporan Pengembalian")){
            try {
                //map.put("d_dari", d_dari);
                //map.put("d_sampai" , d_sampai);

                File report = new File("src/Laporan/Laporan_pengembalian.jrxml");
                design = JRXmlLoader.load(report);
                String sql = "SELECT peminjaman.`id_peminjaman` AS peminjaman_id_peminjaman,"
                        + "peminjaman.`kode_inventaris` AS peminjaman_kode_inventaris,"
                        + "peminjaman.`tanggal_pinjam` AS peminjaman_tanggal_pinjam,"
                        + "peminjaman.`tanggal_kembali` AS peminjaman_tanggal_kembali,"
                        + "peminjaman.`status_peminjaman` AS peminjaman_status_peminjaman,"
                        + "peminjaman.`identitas_peminjam` AS peminjaman_identitas_peminjam,"
                        + "peminjaman.`jumlah_pinjam` AS peminjaman_jumlah_pinjam "
                        + "FROM `peminjaman` peminjaman where status_peminjaman='Kembali'"
                        + "AND tanggal_pinjam BETWEEN '"+ d_dari+"' and '"+d_sampai+"'";
                JRDesignQuery query=new JRDesignQuery();
                query.setText(sql);
                design.setQuery(query);
                jasrep = JasperCompileManager.compileReport(design);
                jaspri = JasperFillManager.fillReport(jasrep, null, con.getconnetion());
                JasperViewer.viewReport(jaspri,false);

            } catch (Exception e) {
                System.out.println(e);
            }
        }else if(jComboBox1.getSelectedItem().equals("Laporan Databarang")) {

            try {

                //map.put("d_dari", d_dari);
                //map.put("d_sampai" , d_sampai);

                File report = new File("src/Laporan/Laporan_databarang.jrxml");
                design = JRXmlLoader.load(report);
                String sql = "SELECT inventaris.`id_inventaris` AS inventaris_id_inventaris,"
                        + "inventaris.`kode_inventaris` AS inventaris_kode_inventaris,"
                        + "inventaris.`nama` AS inventaris_nama,"
                        + "inventaris.`kondisi` AS inventaris_kondisi,"
                        + "inventaris.`keterangan` AS inventaris_keterangan,"
                        + "inventaris.`jumlah` AS inventaris_jumlah,"
                        + "inventaris.`tanggal_register` AS inventaris_tanggal_register,"
                        + "ruang.`nama_ruang` AS ruang_nama_ruang,"
                        + "jenis.`nama_jenis` AS jenis_nama_jenis FROM"
                        + "`ruang` ruang INNER JOIN `inventaris` inventaris ON ruang.`id_ruang` = inventaris.`id_ruang`"
                        + "INNER JOIN `jenis` jenis ON inventaris.`id_jenis` = jenis.`id_jenis`"
                        + "WHERE tanggal_register BETWEEN '"+d_dari+"' AND '"+d_sampai+"'";
                JRDesignQuery query=new JRDesignQuery();
                query.setText(sql);
                design.setQuery(query);
                jasrep = JasperCompileManager.compileReport(design);
                jaspri = JasperFillManager.fillReport(jasrep, null, con.getconnetion());
                JasperViewer.viewReport(jaspri,false);
            } catch (Exception e) {
                System.out.println(e);

            }
        } else if(jComboBox1.getSelectedItem().equals("Laporan DetailPinjam")) {
            try {
                //map.put("d_dari", d_dari);
                //map.put("d_sampai" , d_sampai);

                File report = new File("src/Laporan/Laporan_detailpinjam.jrxml");
                design = JRXmlLoader.load(report);
                String sql1 = "SELECT peminjaman.`id_peminjaman` AS peminjaman_id_peminjaman,"
                        + "peminjaman.`tanggal_pinjam` AS peminjaman_tanggal_pinjam,"
                        + "peminjaman.`tanggal_kembali` AS peminjaman_tanggal_kembali,"
                        + "peminjaman.`status_peminjaman` AS peminjaman_status_peminjaman,"
                        + "peminjaman.`identitas_peminjam` AS peminjaman_identitas_peminjam,"
                        + "peminjaman.`jumlah_pinjam` AS peminjaman_jumlah_pinjam,"
                        + "pegawai.`nama_pegawai` AS pegawai_nama_pegawai,"
                        + "inventaris.`kode_inventaris` AS inventaris_kode_inventaris,"
                        + "inventaris.`nama` AS inventaris_nama, inventaris.`kondisi` AS inventaris_kondisi FROM "
                        + "`pegawai` pegawai INNER JOIN `peminjaman` peminjaman ON pegawai.`id_pegawai` = peminjaman.`id_pegawai`"
                        + "INNER JOIN `inventaris` inventaris ON peminjaman.`kode_inventaris` = inventaris.`kode_inventaris`"
                        + "WHERE tanggal_pinjam BETWEEN '"+d_dari+"' AND '"+d_sampai+"'";
                JRDesignQuery query=new JRDesignQuery();
                query.setText(sql1);
                design.setQuery(query);
                jasrep = JasperCompileManager.compileReport(design);
                jaspri = JasperFillManager.fillReport(jasrep, null, con.getconnetion());
                JasperViewer.viewReport(jaspri,false);
            } catch (Exception e) {
                System.out.println(e);

            }

        } else {

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser tgl1;
    private com.toedter.calendar.JDateChooser tgl2;
    // End of variables declaration//GEN-END:variables
}
